import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import session from '../validations'
import Nav from '@/app/components/Nav'


const inter = Inter( { subsets: ['latin'] } )

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout( {
    children,
}: {
    children: React.ReactNode
} ) {

    const isLogin = session();
    if ( await isLogin ) {
        return (
            <html lang="en" className='bg-gray-800'>

                <body className={inter.className}>
                    <header className='w-full'><Nav /></header>
                    {children}</body>
            </html>
        )
    } else {
        return (

            <html lang="en">
                <body className={inter.className}>

                    <div>
                        <div>Usted no está autorizado para ver esta página.</div>

                        <Link href="/auth/login"> Iniciar sesión </Link>
                        <Link href="/auth/register"> Crear una cuenta</Link>

                    </div>

                </body>
            </html>

        )
    }
}

